// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tc_monitorFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type tc_monitorFlowStats struct {
	_            structs.HostLayout
	Packets      uint64
	Bytes        uint64
	LastSeen     uint64
	FirstSeen    uint64
	LatencySum   uint32
	LatencyCount uint32
	State        uint8
	L7Protocol   uint8
	Pad          [2]uint8
}

type tc_monitorTcpHandshake struct {
	_       structs.HostLayout
	SynTime uint64
	SynSeq  uint32
}

// loadTc_monitor returns the embedded CollectionSpec for tc_monitor.
func loadTc_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tc_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tc_monitor: %w", err)
	}

	return spec, err
}

// loadTc_monitorObjects loads tc_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tc_monitorObjects
//	*tc_monitorPrograms
//	*tc_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTc_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTc_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tc_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_monitorSpecs struct {
	tc_monitorProgramSpecs
	tc_monitorMapSpecs
	tc_monitorVariableSpecs
}

// tc_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_monitorProgramSpecs struct {
	TcMonitor *ebpf.ProgramSpec `ebpf:"tc_monitor"`
}

// tc_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_monitorMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	FlowMap      *ebpf.MapSpec `ebpf:"flow_map"`
	HandshakeMap *ebpf.MapSpec `ebpf:"handshake_map"`
}

// tc_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_monitorVariableSpecs struct {
}

// tc_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTc_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_monitorObjects struct {
	tc_monitorPrograms
	tc_monitorMaps
	tc_monitorVariables
}

func (o *tc_monitorObjects) Close() error {
	return _Tc_monitorClose(
		&o.tc_monitorPrograms,
		&o.tc_monitorMaps,
	)
}

// tc_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTc_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_monitorMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	FlowMap      *ebpf.Map `ebpf:"flow_map"`
	HandshakeMap *ebpf.Map `ebpf:"handshake_map"`
}

func (m *tc_monitorMaps) Close() error {
	return _Tc_monitorClose(
		m.Events,
		m.FlowMap,
		m.HandshakeMap,
	)
}

// tc_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTc_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_monitorVariables struct {
}

// tc_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTc_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_monitorPrograms struct {
	TcMonitor *ebpf.Program `ebpf:"tc_monitor"`
}

func (p *tc_monitorPrograms) Close() error {
	return _Tc_monitorClose(
		p.TcMonitor,
	)
}

func _Tc_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_monitor_bpfel.o
var _Tc_monitorBytes []byte
